### ISSUE TITLE
copy-to-clipboard.js script not found

### ISSUE THREAD

**Issue by bseeger** [globus/django-globus-portal-framework#237]
Hello! 

This file below references `copy-to-clipboard.js`  but that file doesn't appear to be in this project. 

https://github.com/globus/django-globus-portal-framework/blob/9a3adee2ccd15e738c242961ea72348df0823f4c/globus_portal_framework/templates/globus-portal-framework/v2/detail-base.html#L11

Should the file be here, or pull from somewhere else?  

Thanks!

**Comment by NickolausDS** [comment]
Hi @bseeger! Thanks for opening an issue here. And no, you're right, this is missing and should have been included. This will be fixed in the next release.

If you want to fix this for your current deployment before then, you can manually add the js file in the PR above in your project's `static/js/` folder. 

Thanks again, and have a great day!
